package LoginTest.Login;

import java.time.Duration;
import java.util.List;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.support.ui.Select;

public class Practice_Page {

	/**
	 * @param args
	 * @throws InterruptedException
	 */
	public static void main(String[] args) throws InterruptedException {
		// TODO Auto-generated method stub

//********************************Launch Browser***************************************

		// Launch Chrome Browser
		System.setProperty("webdriver.chrome.driver",
				"C:\\Users\\AKDNdHRC\\Selenium\\Training Sessions\\Session 01\\MavenLoginTest\\Login\\chromedriver\\chromedriver.exe");

		WebDriver driver = new ChromeDriver();

		// Wait 10 Seconds
		driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(60));
		driver.manage().timeouts().scriptTimeout(Duration.ofSeconds(30));
		driver.manage().timeouts().pageLoadTimeout(Duration.ofSeconds(60));

//********************************Open Browser*****************************************		

		// Browser Open in Maximise Window
		driver.manage().window().maximize();

		// Wait 10 Seconds
		driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(10));
		driver.manage().timeouts().scriptTimeout(Duration.ofSeconds(30));
		driver.manage().timeouts().pageLoadTimeout(Duration.ofSeconds(60));

//*******************************Login Page********************************************		

		// Open URL EMR Staging Site (Login Page)
		driver.get("https://emrunitclerk.virtualdoc.akdndhrc.org/#/emrfrontend/");

		// Locate User name By CSS Locator -- [tag#id] -- CSS Locator # 01
		driver.findElement(By.cssSelector("input#mat-input-0")).sendKeys("asher.hussnain@aku.edu");

		// Locate Password by By CSS Locator -- (tag[attribute=value]) -- CSS Locator #
		// 03
		driver.findElement(By.cssSelector("input[type=password]")).sendKeys("asher12");

		// Locate Login Button by CSS Locator using [tag.value of class name] -- CSS
		// Locator # 02
		driver.findElement(By.cssSelector("button.btn-Signin")).click();

		// Flow
		System.out.println("Step# 01: Successfully Login the App");

// ****************************Dashboard************************************************

		// In Dashboard Click on "Register New Patient" Button

		// Switch to Product Page
		String currWindoeHanle = driver.getWindowHandle();
		driver.switchTo().window(currWindoeHanle);

		// Wait 2 seconds
		driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(10));
		driver.manage().timeouts().scriptTimeout(Duration.ofSeconds(30));
		driver.manage().timeouts().pageLoadTimeout(Duration.ofSeconds(60));

		// Locate Registration Button by Xpath
		// driver.findElement(By.xpath("//button[@Class='btn-RegNewPatient']")).click();
		driver.findElement(By.xpath("/html/body/app-root/app-emrhome/div/div[2]/div/div[1]/div[1]/button")).click();

		// Flow
		System.out.println("Step# 02: In Dashboard Click on 'REGISTER NEW PATIENT' Button ");

// ********************************Registration Form************************************

		// Patient Registration Form Fill

		// Wait 2 seconds
		driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(10));
		driver.manage().timeouts().scriptTimeout(Duration.ofSeconds(30));
		driver.manage().timeouts().pageLoadTimeout(Duration.ofSeconds(60));

// *******************************Field #01 MR No***************************************

		// 1. MR No is Mandatory Field but auto generated by App

// *******************************Field #02 AKU MR No***********************************

		// 2. AKU MR No is Mandatory Field Locate By XPath
		driver.findElement(By.xpath(
				"/html/body/app-root/app-patient-registration/div/mat-card/form/div/div[2]/mat-form-field/div/div[1]/div[3]/input"))
				.sendKeys("123-45-67");

// *******************************Field #03 Sehat Safar No******************************

		// 3. Sehat Safar No is Optional Field Locate By XPath
		driver.findElement(By.xpath(
				"/html/body/app-root/app-patient-registration/div/mat-card/form/div/div[3]/mat-form-field/div/div[1]/div[3]/input"))
				.sendKeys("S12345678");

// *******************************Field #04 CNIC No*************************************

		// 4. CNIC No is Optional Field Locate By XPath
		driver.findElement(By.xpath(
				"/html/body/app-root/app-patient-registration/div/mat-card/form/div/div[4]/mat-form-field/div/div[1]/div[3]/input"))
				.sendKeys("1234567890123");

		// Wait 2 seconds
		driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(10));
		driver.manage().timeouts().scriptTimeout(Duration.ofSeconds(30));
		driver.manage().timeouts().pageLoadTimeout(Duration.ofSeconds(60));

// *******************************Field #05 First Name**********************************

		// 5. First Name is Mandatory Field Locate By XPath
		driver.findElement(By.xpath(
				"/html/body/app-root/app-patient-registration/div/mat-card/form/div/div[5]/mat-form-field/div/div[1]/div[3]/input"))
				.sendKeys("TestTen");

// *******************************Field #06 Middle Name*********************************

		// 6. Middle Name is Optional Field Locate By XPath
		driver.findElement(By.xpath(
				"/html/body/app-root/app-patient-registration/div/mat-card/form/div/div[6]/mat-form-field/div/div[1]/div[3]/input"))
				.sendKeys("NewTen");

// *******************************Field #07 Last Name***********************************

		// 7. Last Name is Mandatory Field Locate By XPath
		driver.findElement(By.xpath(
				"/html/body/app-root/app-patient-registration/div/mat-card/form/div/div[7]/mat-form-field/div/div[1]/div[3]/input"))
				.sendKeys("PatientTen");

// *******************************Field #08 Gender**************************************

		// 8. Gender dropdown trigger is Mandatory Field Locate By XPath
		WebElement GenderdropdownTrigger = driver.findElement(By.xpath("//*[@id=\"mat-select-0\"]"));
		GenderdropdownTrigger.click();

//		// 8.1 Gender dropdown options Male Locate By XPath
//		WebElement male = driver.findElement(By.xpath("//mat-option[@id='mat-option-0']//span"));
//		male.click();
//
		// 8.2 Gender dropdown options Female Locate By XPath
		WebElement female = driver.findElement(By.xpath("//mat-option[@id='mat-option-1']//span"));
		female.click();

//		// 8.3 Gender dropdown options Other Locate By XPath
//		// WebElement other =
//		// driver.findElement(By.xpath("//mat-option[@id='mat-option-2']//span"));
//		// other.click();

		// Wait 2 seconds
		driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(10));
		driver.manage().timeouts().scriptTimeout(Duration.ofSeconds(30));
		driver.manage().timeouts().pageLoadTimeout(Duration.ofSeconds(60));

// *******************************Field #09 Email***************************************

		// 9. Email is Optional Field Locate By XPath
		driver.findElement(By.xpath(
				"/html/body/app-root/app-patient-registration/div/mat-card/form/div/div[9]/mat-form-field/div/div[1]/div[3]/input"))
				.sendKeys("Testing123@gmail.com");

// *******************************Field #10 Phone No************************************

		// 10. Phone No is Mandatory Field Locate By XPath
		driver.findElement(By.xpath(
				"/html/body/app-root/app-patient-registration/div/mat-card/form/div/div[10]/mat-form-field/div/div[1]/div[3]/input"))
				.sendKeys("03127653445");

// *******************************Field #11 Alternate Phone No**************************

		// 11. Alternate Phone No is Optional Field Locate By XPath
		driver.findElement(By.xpath(
				"/html/body/app-root/app-patient-registration/div/mat-card/form/div/div[11]/mat-form-field/div/div[1]/div[3]/input"))
				.sendKeys("02167653445");

// *******************************Field #12 City Town***********************************

		// 12. City Town is Mandatory Field but App set Value 'Karachi' By Default
		driver.findElement(By.xpath(
				"/html/body/app-root/app-patient-registration/div/mat-card/form/div/div[12]/mat-form-field/div/div[1]/div[3]/input"))
				.clear(); // Clear text from field
		driver.findElement(By.xpath(
				"/html/body/app-root/app-patient-registration/div/mat-card/form/div/div[12]/mat-form-field/div/div[1]/div[3]/input"))
				.sendKeys("Hyderabad");

		// Wait 2 seconds
		driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(10));
		driver.manage().timeouts().scriptTimeout(Duration.ofSeconds(30));
		driver.manage().timeouts().pageLoadTimeout(Duration.ofSeconds(60));

// *******************************Field #13 DOB*****************************************	
// =============================== Method # 01 =========================================

		// 13. DOB is Mandatory Field Locate By XPath

//		driver.findElement(By.xpath(
//				"/html/body/app-root/app-patient-registration/div/mat-card/form/div/div[13]/mat-form-field/div/div[1]/div[3]/input"))
//				.sendKeys("05/04/1993");

// =============================== Method # 02 =========================================
		// Input DOB
//		String Year = "2024";
//		String Month = "JAN";
//		String Date = "12";
//
//		driver.findElement(By.xpath(
//				"/html/body/app-root/app-patient-registration/div/mat-card/form/div/div[13]/mat-form-field/div/div[1]/div[4]/mat-datepicker-toggle/button"))
//				.click();
//		
		// Year and Month Selection
//		while (true) {
//			String MonthYear = driver.findElement(By.xpath(" //button[@aria-label='Choose month and year']")).getText();
//			System.out.println(MonthYear);
//
//			String arr[] = MonthYear.split(" ");
//			String mon = arr[0];
//			String yr = arr[1];
//
//			if (mon.equalsIgnoreCase(Month) && yr.equals(Year))
//				break;
//			else
//				driver.findElement(By.xpath("//button[@aria-label='Previous month']")).click();
//
//		}
//
//		// Date Selection
//		List<WebElement> allDates = driver.findElements(By.xpath(
//				"//*[@id=\"mat-datepicker-0\"]/div/mat-month-view/table/tbody//td"));
//
//		for (WebElement ele : allDates) {
//			String dt = ele.getText();
// 
//			if (dt.equals(Date)) {
//				ele.click();
//				break;
//			}
//		}

// =============================== Method # 03 =========================================
//		// Input DOB	
//		String Year = "2008";
//		String Month = "SEPT";
//		String Date = "21";
//
//		// Open Calendar
//		driver.findElement(By.xpath(
//		        "/html/body/app-root/app-patient-registration/div/mat-card/form/div/div[13]/mat-form-field/div/div[1]/div[4]/mat-datepicker-toggle/button"))
//		        .click();
//
//		// Click Month and Year Button
//		driver.findElement(By.xpath("//button[@aria-label='Choose month and year']")).click();
//
//		// **Year Selection (Dynamic Loop)**
//		while (true) {
//		    List<WebElement> allYears = driver.findElements(By.xpath("//*[@id=\"mat-datepicker-0\"]/div/mat-multi-year-view/table/tbody//td"));
//		    
//		    boolean yearFound = false;
//		    
//		    for (WebElement element : allYears) {
//		        if (element.getText().equals(Year)) {
//		            element.click();
//		            yearFound = true;
//		            break;
//		        }
//		    }
//		    
//		    if (yearFound) break; // Exit loop once the year is found and clicked
//		    
//		    // Click Previous Year Button if the desired year is not in the current range
//		    driver.findElement(By.xpath("//button[@aria-label='Previous 24 years']")).click();
//		}
//
//		// **Month Selection**
//		List<WebElement> allMonths = driver.findElements(By.xpath("//*[@id=\"mat-datepicker-0\"]/div/mat-year-view/table/tbody//td"));
//
//		for (WebElement element : allMonths) {
//		    if (element.getText().equals(Month)) {
//		        element.click();
//		        break;
//		    }
//		}
//
//		// **Date Selection**
//		List<WebElement> allDates = driver.findElements(By.xpath("//*[@id=\"mat-datepicker-0\"]/div/mat-month-view/table/tbody//td"));
//
//		for (WebElement element : allDates) {
//		    if (element.getText().equals(Date)) {
//		        element.click();
//		        break;
//		    }
//		}

// *******************************Field #14 Age(Years)***********************************
//
//		// 14. Age(Years) is Mandatory Field generate value on Click when DOB is filled Locate By XPath
//		driver.findElement(By.xpath(
//				"/html/body/app-root/app-patient-registration/div/mat-card/form/div/div[14]/mat-form-field/div/div[1]/div[3]"))
//				.click();

		// 14. Age(Years) is Mandatory Field generate value on Click Locate By XPath
		String Age = "62";
		driver.findElement(By.xpath(
				"/html/body/app-root/app-patient-registration/div/mat-card/form/div/div[14]/mat-form-field/div/div[1]/div[3]/input"))
				.sendKeys(Age);

// *******************************Field #15 Province************************************

		// 15. Province dropdown trigger is Mandatory Field Locate By XPath
		WebElement ProvinceropdownTrigger = driver.findElement(By.xpath(
				"/html/body/app-root/app-patient-registration/div/mat-card/form/div/div[15]/mat-form-field/div/div[1]/div[3]/mat-select"));
		ProvinceropdownTrigger.click();

//		// 15.1 Province dropdown options Sindh Locate By XPath
//		WebElement Sindh = driver.findElement(By.xpath("//span[@class='mat-option-text'][normalize-space()='Sindh']"));
//		Sindh.click();

		// 15.2 Province dropdown options Punjab Locate By XPath
		// WebElement Punjab =
		// driver.findElement(By.xpath("//span[normalize-space()='Punjab']"));
		// Punjab.click();

		// 15.3 Province dropdown options Balochistan Locate By XPath
		WebElement Balochistan = driver.findElement(By.xpath("//span[normalize-space()='Balochistan']"));
		Balochistan.click();

//		// 15.4 Province dropdown options KPK Locate By XPath
//		 WebElement KPK = driver.findElement(By.xpath("//span[normalize-space()='KPK']"));
//		 KPK.click();

// *******************************Field #16 Home Address************************************

		// 16. Home Address is Optional Field Locate By XPath
		driver.findElement(By.xpath(
				"/html/body/app-root/app-patient-registration/div/mat-card/form/div/div[16]/mat-form-field/div/div[1]/div[3]/input"))
				.sendKeys("Block# 15, Street# 8, House# 765. Gulshan Ghazi");

		// Wait 2 seconds
		driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(10));
		driver.manage().timeouts().scriptTimeout(Duration.ofSeconds(30));
		driver.manage().timeouts().pageLoadTimeout(Duration.ofSeconds(60));

// *******************************Field #17 Marital Status**********************************

		// 17. Marital Status dropdown trigger is Mandatory Field Locate By XPath
		WebElement MaritalStatusDropdownTrigger = driver.findElement(By.xpath(
				"/html/body/app-root/app-patient-registration/div/mat-card/form/div/div[17]/mat-form-field/div/div[1]/div[3]/mat-select/div/div[1]/span"));
		MaritalStatusDropdownTrigger.click();

//		// 17.1 Marital Status dropdown options Married Locate By XPath
//		WebElement Married = driver.findElement(By.xpath("//span[normalize-space()='Married']"));
//		Married.click();

//		// 17.2 Marital Status dropdown options Unmarried Locate By XPath
//		WebElement UnMarried = driver.findElement(By.xpath("//span[normalize-space()='Unmarried']"));
//		UnMarried.click();

//		// 17.3 Marital Status dropdown options Divorce Locate By XPath
//		WebElement Divorce = driver.findElement(By.xpath("//span[normalize-space()='Divorce']"));
//		Divorce.click();

		// 17.4 Marital Status dropdown options Widow Locate By XPath
		WebElement Widow = driver.findElement(By.xpath("//span[normalize-space()='Widow']"));
		Widow.click();

//		// 17.5 Marital Status dropdown options Others Locate By XPath
//		WebElement Others = driver.findElement(By.xpath("//span[normalize-space()='Others']"));
//		Others.click();

// *******************************Field #18 Type of Visit**********************************

		// 18. Type of Visit dropdown trigger is Mandatory Field Locate By XPath
		WebElement TyoeOfVisitDropdownTrigger = driver.findElement(By.xpath(
				"/html/body/app-root/app-patient-registration/div/mat-card/form/div/div[18]/mat-form-field/div/div[1]/div[3]/mat-select/div/div[1]/span"));
		TyoeOfVisitDropdownTrigger.click();

		// 18.1 Type of Visit dropdown options Clinical Locate By XPath
		WebElement Clinical = driver.findElement(By.xpath("//span[normalize-space()='Clinical']"));
		Clinical.click();

//		// 18.2 Type of Visit dropdown options Educational Locate By XPath
//		WebElement Educational = driver.findElement(By.xpath("//span[normalize-space()='Educational']"));
//		Educational.click();

//		// 18.3 Type of Visit dropdown options Immunization Visit Locate By XPath
//		WebElement ImmunizationVisit = driver.findElement(By.xpath("//span[normalize-space()='Immunization Visit']"));
//		ImmunizationVisit.click();

//		// 18.4 Type of Visit dropdown options Others Locate By XPath
//		WebElement Otherss = driver.findElement(By.xpath("//span[normalize-space()='Others']"));
//		Otherss.click();

		// Wait 2 seconds
		driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(10));
		driver.manage().timeouts().scriptTimeout(Duration.ofSeconds(30));
		driver.manage().timeouts().pageLoadTimeout(Duration.ofSeconds(60));

// *******************************Patient Registration Form Done****************************

		// Flow
		System.out.println("Step# 03: Registration Form Fill Successfully Done");

// *******************************Submit Patient Registration Form**************************

		// Click on Register Button Locate By XPath
		driver.findElement(By.xpath("//button[@class='btn-Submit olfcss']")).click();

		// Flow
		System.out.println("Step# 04: New Patient Register Successfully Done");

		// Wait 2 seconds
		driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(10));
		driver.manage().timeouts().scriptTimeout(Duration.ofSeconds(30));
		driver.manage().timeouts().pageLoadTimeout(Duration.ofSeconds(60));

// ***********************************Book Appointment**************************************

		// Click on Book Appointment Button Locate By XPath
		driver.findElement(By.xpath("//button[@class='btn-Appointment olfcss']")).click();

		// Flow
		System.out.println("Step# 05: Book Appointment");

		// Wait 2 seconds
		driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(10));
		driver.manage().timeouts().scriptTimeout(Duration.ofSeconds(30));
		driver.manage().timeouts().pageLoadTimeout(Duration.ofSeconds(60));

// ***********************************Search Doctor*****************************************

		Thread.sleep(2000);

		// Specialities List dropdown trigger is Optional Field Locate By XPath
		WebElement SpecialitiesdownTrigger = driver.findElement(By.xpath(
				"/html/body/app-root/app-search-doctor/div/mat-card/form/div[1]/div[1]/mat-form-field/div/div[1]/div[3]/mat-select/div"));
		SpecialitiesdownTrigger.click();

		// Specialities List dropdown options Family Medicine Locate By XPath
		WebElement FamilyMedicine = driver.findElement(By.xpath("//span[@class='mat-option-text']"));
		FamilyMedicine.click();

		// Wait 2 seconds
		driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(10));
		driver.manage().timeouts().scriptTimeout(Duration.ofSeconds(30));
		driver.manage().timeouts().pageLoadTimeout(Duration.ofSeconds(60));

		// Search Doctor by Specific Name "Dr. Sabeen Shah"
		driver.findElement(By.xpath(
				"/html/body/app-root/app-search-doctor/div/mat-card/form/div[1]/div[2]/mat-form-field/div/div[1]/div[3]/input"))
				.sendKeys("Dr. Sabeen Shah");

		// Click on Search Button Locate By XPath
		driver.findElement(By.xpath("//button[@class='btn-Search mr-4']")).click();

		// Flow
		System.out.println("Step# 06: Search Doctor by Specific Name");

// ***********************************Select Doctor*****************************************

		Thread.sleep(2000);

		// Click on Select Button Locate By XPath
		driver.findElement(By.xpath("//button[@class='btn-Select select-css']")).click();

		// Wait 2 seconds
		driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(10));
		driver.manage().timeouts().scriptTimeout(Duration.ofSeconds(30));
		driver.manage().timeouts().pageLoadTimeout(Duration.ofSeconds(60));

		// Flow
		System.out.println("Step# 07: Select Doctor by Specific Name");

// ***********************************Select Schedule*****************************************

		Thread.sleep(2000);

		// Click on Select Schedule Button Locate By XPath
		driver.findElement(By.xpath(
				"/html/body/app-root/app-doctorschedule/div/mat-card/div/div[1]/mat-card/mat-card-actions/button"))
				.click();

		// Wait 2 seconds
		driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(10));
		driver.manage().timeouts().scriptTimeout(Duration.ofSeconds(30));
		driver.manage().timeouts().pageLoadTimeout(Duration.ofSeconds(60));

		// Flow
		System.out.println("Step# 08: Select Schedule");

// ***********************************Select Slot*********************************************

		Thread.sleep(2000);

		// Click on Select Slot Button Locate By XPath
		driver.findElement(By.xpath("//button[@class='mat-focus-indicator btn-Book mt-1 mat-button mat-button-base']"))
				.click();

		// Wait 2 seconds
		driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(10));
		driver.manage().timeouts().scriptTimeout(Duration.ofSeconds(30));
		driver.manage().timeouts().pageLoadTimeout(Duration.ofSeconds(60));

		// Flow
		System.out.println("Step# 09: Select Slot");

// ***********************************Appointment Confirmation*********************************

		Thread.sleep(2000);

		// Click on CONFIRM APPOINTMENT WITH PAY Button Locate By XPath
		driver.findElement(By.xpath("//button[@class='btn-ConfirmApp left']")).click();

		// Flow
		System.out.println("Step# 10: Confirm Appointment With Pay");

		// Wait 2 seconds
		driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(10));
		driver.manage().timeouts().scriptTimeout(Duration.ofSeconds(30));

// ***************************************Payment***********************************************

		Thread.sleep(20000);

		// Switch to Product Page
		String currWindoeHanle1 = driver.getWindowHandle();
		driver.switchTo().window(currWindoeHanle1);

		// Discount dropdown trigger is Mandatory Field Locate By XPath
		WebElement DiscountDropdownTrigger = driver
				.findElement(By.xpath("/html/body/app-root/app-paymentsummary/div/mat-card/table/tr[8]/td/select"));
		DiscountDropdownTrigger.click();

		// Discount dropdown options Default (Pkr. 750) Locate By XPath
		WebElement Default = driver.findElement(
				By.xpath("/html/body/app-root/app-paymentsummary/div/mat-card/table/tr[8]/td/select/option[2]"));
		Default.click();

//		// Discount dropdown options Adults (Pkr. 650) Locate By XPath
//		WebElement Adults = driver.findElement(
//				By.xpath("/html/body/app-root/app-paymentsummary/div/mat-card/table/tr[8]/td/select/option[3]"));
//		Adults.click();
//
//		// Discount dropdown options Zero (Pkr. 0) Locate By XPath
//		WebElement Zero = driver.findElement(
//				By.xpath("/html/body/app-root/app-paymentsummary/div/mat-card/table/tr[8]/td/select/option[4]"));
//		Zero.click();
//
//		// Discount dropdown options YPH (Pkr. 300) Locate By XPath
//		WebElement YPH = driver.findElement(
//				By.xpath("/html/body/app-root/app-paymentsummary/div/mat-card/table/tr[8]/td/select/option[5]"));
//		YPH.click();
//
//		// Discount dropdown options Peads (Pkr. 500) Locate By XPath
//		WebElement Peads = driver.findElement(
//				By.xpath("/html/body/app-root/app-paymentsummary/div/mat-card/table/tr[8]/td/select/option[6]"));
//		Peads.click();
//
//		// Discount dropdown options Service Charges (Pkr. 150) Locate By XPath
//		WebElement ServiceCharges = driver.findElement(
//				By.xpath("/html/body/app-root/app-paymentsummary/div/mat-card/table/tr[8]/td/select/option[7]"));
//		ServiceCharges.click();
//
//		// Discount dropdown options Discounted Fees (Pkr. 650) Locate By XPath
//		WebElement DiscountedFees = driver.findElement(
//				By.xpath("/html/body/app-root/app-paymentsummary/div/mat-card/table/tr[8]/td/select/option[8]"));
//		DiscountedFees.click();

		// Wait 2 seconds
		driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(10));
		driver.manage().timeouts().scriptTimeout(Duration.ofSeconds(30));
		driver.manage().timeouts().pageLoadTimeout(Duration.ofSeconds(60));

		// Flow
		System.out.println("Step# 11: Payment Confirmed");

// ***********************************Print Invoice Thermal*********************************

		// Click on PRINT INVOICE (Thermal) Button Locate By XPath
		driver.findElement(By.xpath("/html/body/app-root/app-confirmpayment/div/mat-card/mat-card-actions/button[1]"))
				.click();
		driver.getWindowHandles().forEach(tab -> driver.switchTo().window(tab));

		// Wait 2 seconds
		driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(10));
		driver.manage().timeouts().scriptTimeout(Duration.ofSeconds(30));
		driver.manage().timeouts().pageLoadTimeout(Duration.ofSeconds(60));

		// Flow
		System.out.println("Step# 10: Confirm Appointment With Pay");

	}
}
